### ISSUE TITLE
[Proposal] Change source code to be compatible with Octave

### ISSUE THREAD

**Issue by jacob-umich** [zzhuyii/OrigamiSimulator#3]
## Description
Octave is an alternative interpreter to MATLAB that shares most of its functionality but is open-source. However, not all functionality is shared. This issue identifies that string comparisons must be done with `strcmp()` instead of `==`.

## Tasks
- [x] #5
- [x] #6

**Comment by zzhuyii** [comment]
Hi Jacob, 

I had investigated this a little. I think the best option is to start an Octave compatible branch for you and keep it separate from the main. For the main, what I have been doing is not to publish anything unless it is finish (because others are expected to be visiting this branch all the time). I want to keep it like that (which means that it is not updated unless there is a stable and major update). 

There are a couple ongoing coding happening in the "Solver_Solve", where I am integrating some dynamic simulation capability for PZT micro-origami. This is conflicting with the pull request you submitted, so I have to revert it.  Let's try to figure out a new branch for Octave compatibility recently. 

Best, 
Yi
